### ISSUE TITLE
Create a class which handle add/update/delete data of wp user

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#1987]
## Issue Overview

Currently, we have code inside Give functions which will keep update wp user when donor update.  I think we can create a class which handles this and keeps sync ( by hook ) wp user with the donor.
We can use following hooks:
`give_post_insert_donor` ( need some hook for primary table ), `add_donor_metadata`, `update_donor_metadata` and `delete_donor_metadata`.

## Related Issue
#1482 

## Todos
- [ ] Find which info we need to sync with wp user for donor
- [ ] Find hooks to update wp user
- [ ] Create this functionality with singleton class
- [ ] Test
- [ ] Documentation

**Comment by ravinderk** [comment]
@DevinWalker Reopening this issue because this closed by the wrong mention in other issue related PR.

**Comment by mikejhale** [comment]
Closing due to being stale
