### ISSUE TITLE
refactor(admin-shortcode): use Modal API to for shortcode builder panel

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3008]
## User Story
As a `developer`, I want shortcode builder panel more robust and easy to use.
Currently, we are facing challenges to create the multi-select and ajaxify field. With Modal API it will be easy to achieve that.

![tgaxvoklgr 1](https://user-images.githubusercontent.com/1784821/38536382-83077808-3ca6-11e8-85ca-33f20dcbde41.gif)

## Tasks
- [ ] Research how to integrate Modal API with shortcode button.
- [ ] When upgrading shortcode builder API then create field support:
    - [ ] Text Field ( add support for different field type like number etc.)
    - [ ] Radio Field
    - [ ] Select Field ( with/without chosen )
    - [ ] Multi Select Field ( with/without chosen )
- [ ] Testing:
  - [ ] Shortcode will alway insert on last cursor position in editor.
  - [ ] Check with a single editor
  - [ ] Check with Multi editor on page

For ref:
https://github.com/WordImpress/Give/issues/1475
https://github.com/WordImpress/Give/issues/1472#issuecomment-356290217

**Comment by mikejhale** [comment]
Closing as we won't focus on the shortcodes as Gutenberg blocks will be replacing these.
