### ISSUE TITLE
feat: add Stats API

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3195]
## User Story

As an `admin`, I want `reports` to generate faster for large DB so that performance is improved.

As a `developer` I want an easy way to `query report data` using an `API that's easy to interact with`. 

**Predefined report periods:**

![image](https://user-images.githubusercontent.com/1784821/39755868-0a6cca1a-52e5-11e8-9690-affe0bc5d512.png)

## Current Behavior
Earning calculation logic runs when page load or admin request for it. On the page load, a calculation can cause of `500` error.

## Expected Behavior
Way to calculation earning on time on donation completes (async process if needed).

## Related

https://docs.google.com/document/d/1bOo3NDyCwTGXxxqXq568bOC8TeNQKOUzYk-fah6-tSw/edit#

## Acceptance Criteria
The main focus of Stats API is to get date based sale and earning data. There is the following area where we will start using this:
- [x] Dashboard Give widget
- [ ] Donor Listing Page
- [ ] Donor detail page
- [x] Donor wall shortcode ( done in https://github.com/impress-org/give/issues/3744 )
- [ ] Addons (_need to check_)

**Comment by kevinwhoffman** [comment]
@ravinderk Can you provide an update on this issue before this week's call? I would like to see this converted to an epic and broken out into smaller issues with acceptance criteria so that we can get a better sense of the progress being made. I see the commits, but it's hard to understand what they are working towards. Thanks.

**Comment by ravinderk** [comment]
@kevinwhoffman I agreed with you. I will make this issue `Epic` with subtasks.

**Comment by ravinderk** [comment]
@kevinwhoffman @DevinWalker We updating donor wall logic that gives us the idea to improve meta query to get stats. I am closing this issue in favor of creating a new one with update scope and acceptance criteria.
