### ISSUE TITLE
feat: add documentation links to shortcode builder

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3233]
## User Story
As a Give user I want to be able to learn about all features of Give by navigating the plugin. If there are additional features of a tool which need detailed explanation, I expect a link to the full documentation to be present in the plugin UI.

This problem is most evident with the Give Form Grid shortcode, but all the shortcodes in the builder would benefit from this update.

## Current Behavior

Currently, there are features of the Donation Form Grid shortcode that are only discoverable via the online documentation. If I'm just using the plugin UI, specifically the shortcode builder, I would never be able to learn about these additional features. 

## Expected Behavior

I expect to find a link to documentation that informs me that there are additional features that I can learn about.

## Possible Solution

Add logic into the shortcode builder UI that allows us to output links to documentation in a similar fashion to our current Settings API. 

See Visuals below for an example

## Visuals

![image](https://user-images.githubusercontent.com/930724/40210626-c32c3664-59fa-11e8-8e5f-ab155ddeebae.png)

## Tasks
- [x] The logic should be added into the shortcode builder settings
- [x] Text and links should be added to each of the shortcode builder options. 
    - [x] "Learn more about the Donation Form Shortcode" (link: http://docs.givewp.com/shortcode-give-forms)
    - [x] "Learn more about the Goal Shortcode" (link: http://docs.givewp.com/shortcode-give-goal)
    - [x] "Learn more about the Give Login Shortcode" (link: http://docs.givewp.com/shortcode-give-login)
    - [x] "Learn more about the Give Register Shortcode" (link: http://docs.givewp.com/shortcode-give-register)
    - [x] "Learn more about the Give Profile Editor Shortcode" (link: http://docs.givewp.com/shortcode-profile-editor)
    - [x] "Learn more about the Donation Form Grid Shortcode" (link: http://docs.givewp.com/shortcode-form-grid)
    - [x] "Learn more about the Donation History Shortcode" (link: http://docs.givewp.com/shortcode-donation-history)
    - [x] "Learn more about the Donation Receipt Shortcode" (link: http://docs.givewp.com/shortcode-donation-receipt)
    - [x] "Learn more about the Donation Totals Shortcode" (link: http://docs.givewp.com/shortcode-donation-totals)
- [ ] All shortlinks have already been created, but confirm that all redirect properly after implementation

**Comment by ravinderk** [comment]
@mathetos This link is not working for me http://docs.givewp.com/shortcode-donation-totals

**Comment by mathetos** [comment]
Updated. Works as expected now

**Comment by mathetos** [comment]
Here's the new shortlink for donor wall:
http://docs.givewp.com/shortcode-donor-wall

Thanks!
