### ISSUE TITLE
refactor(donation): replace and improve existing data api built on jquery to es6

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#3326]
## User Story
As a developer, I want to use the data API in add-ons to leverage the existing calculations so that I don't need to perform calculation again in the addons.

## Current Behavior
I currently can see the challenges with using jquery data API in es6 scripted add-ons like Stripe due to which we have to manually do calculations in es6. Also, there are challenges with jquery ajax when donate button click event need to be handled.

## Expected Behavior
I expect to streamline the data API using javascript and improve it further so that we can leverage the benefits within add-ons as we will be using ES6 everywhere in future.

## Tasks
- [ ] Convert current data api ( i.e. Give.fn.xxx or Give.form.xxx ) usingn jquery to es6
- [ ] Test with addons
- [ ] Test for IE compatibility

**Comment by DevinWalker** [comment]
Closing to focus more on refactoring the forms within add-on from jQuery to ES6 + React.
