### ISSUE TITLE
feat(form): prevent live-mode donations reverting to test gateway

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#3608]
## User Story
As a `give admin`, I want `my form to stop taking donations altogether in the event that my enabled gateway becomes deactivated` so that `donors don't errantly enter test mode donations and become confused`.

## Current Behavior
Currently, if a site has (for example) the Stripe gateway set as the only enabled gateway in the Payment Gateway settings and the Stripe add-on is deactivated, the site reverts to enabling the test gateway on the front end, and donors are confused. 

## Expected Behavior
I expect that if no gateways are active, the form is disabled with an instructive error message. This message should be filterable and instructive to the donor that the site is not currently accepting live donations.

## Possible Solution
**If** the site is not in test mode

**And** the enabled gateways are all inactive for some reason

**Then** display this message as an Amber-level notice. (not a bright red error)
```
This donation form is currently disabled. 
For questions, please contact a site administrator.
```
## Steps to Reproduce
1. Activate any premium gateway, and enable _only_ that gateway on a form (can be site-wide or per-form with the add-on)
2. Deactivate the entire add-on on the plugins page, but don't re-save the settings.
3. Attempt a donation on that form.

It is a test mode donation, and to the donor, it looks like money changed hands without a card, which is confusing (at best).

## Related
- https://secure.helpscout.net/conversation/639928785/23373?folderId=848135

## Tasks
- [ ] prevent live mode donation forms from accepting donations when no gateways are enabled.
- [ ] test the fix with the per form gateways add-on to ensure it works there as well.
- [ ] ensure that the error message is filterable for developers.
- [ ] provide a callback function to modify the snippet for inclusion in our snippet library

**Comment by kevinwhoffman** [comment]
Discussed with @DevinWalker. Closing as wontfix because if the only live gateway on the site is deactivated, we think the admin should understand that the form can no longer accept donations.
