### ISSUE TITLE
feat: add setting for featured image position

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3620]
## User Story

As a Site admin, I want to be able to design my Give single form pages with more flexibility specifically regarding the featured image position.

## Current Behavior

Currently, it is always only displayed in the Give Sidebar. If I want to have my single form pages displayed full width without a sidebar, I can disable the sidebar, but then the featured image is gone as well. The only ways to add the featured image once the sidebar is disabled is to either add it directly into the Form Content, or via a PHP hook.

## Expected Behavior

I expect to have options for the featured image display that are intuitive and leverage the featured image metabox properly rather than do workarounds in the content or via hooks.

## Possible Solution
This is my suggestion. Add this into "Settings > Display Options > Post Types"

![image](https://user-images.githubusercontent.com/930724/44341805-dfd46880-a43d-11e8-8093-cbbeda387183.png)

This would then make the "Form Featured Image" setting redundant and unnecessary. Perhaps for backward compatibility we simply update that existing option, keeping it's settings name but adding new options.

## Tasks

- [ ] Add the setting to the right place in the Settings UI.
- [ ] Ensure that each setting works as intended. For example:
* If the "Single Form Sidebar" setting is set to disabled, and the "Featured Image Position" setting is set to "Sidebar", the sidebar should still be removed as it is currently.
* But if the Single Form Sidebar is enabled, and the Featured Image Position is set to "Above the Form Content" then it should appear there correctly. Same with if the sidebar is disabled.
- [ ] Ensure that these settings also work as intended in combination with the Featured Image Size
- [ ] Depending on how you addressed the existing "Featured Image" setting, ensure backwards compatibility.

**Comment by kevinwhoffman** [comment]
I agree this would be especially helpful for certain themes where floating an image to the left creates an awkwardly narrow form.

> This [new setting] would then make the "Form Featured Image" setting redundant and unnecessary. Perhaps for backward compatibility we simply update that existing option, keeping it's settings name but adding new options.

Good point to keep in mind during implementation.

**Comment by kevinwhoffman** [comment]
After discussing with @DevinWalker, we're going to icebox as we don't want to further complicate those options at this time.

**Comment by mikejhale** [comment]
Closing as there is a workaround.
