### ISSUE TITLE
feat: develop Stat API that's performant and easily understandable

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3721]
I will complete this issue after completing #3722 #3723 

## TODO
- [x] research which data we need to get faster stat results 
- [x] create a database table for donation stats [ table created]
- [x] research about the best way to update donation stats in the custom table [ We will use background update ]
- [ ] update core to use Stat API
- [ ] create Stat API helper functions to easily get data

**Comment by ravinderk** [comment]
Closing in favor of https://github.com/impress-org/give/issues/3195#issuecomment-434168090
